org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# NeoForge Properties
minecraft_version=26.1
minecraft_version_range=[26.1, 26.1.1]
neo_version=26.1.0.19-beta
loader_version_range=[4,)

# Mod Properties
mod_id=yakisugi
mod_name=Yakisugi
mod_license=Yakisuki Mod License
mod_version=26.09.18-26.1-neoforge
mod_group_id=com.axperty
mod_credits=Axperty, Ateneah, Nezxo, takeamuke, Lorenzo N, Mash D, oRandomy
mod_authors=Axperty
mod_description=Yakisugi is a mod that adds Japanese inspired elements such as charred wood variants, traditional decorations, weapons, and straw armor.
